title: Eyemaster
description: Privacy policy and support contact for Eyemaster

baseurl: ""
url: "https://eyemaster.github.io"
github_username: samyeule

theme: just-the-docs
color_scheme: custom

search_enabled: false

footer_content: "Copyright &copy; 2026 samyeule"

exclude:
  - Gemfile
  - Gemfile.lock
